default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ota

development:
  <<: *default
  database: afc_mobile_admin_development

test:
  <<: *default
  database: afc_mobile_admin_test

production:
  <<: *default
  database: afc_mobile_admin_production
  password: <%= ENV['AFC_MOBILE_ADMIN_DATABASE_PASSWORD'] %>

